name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v13
        with:
          name: fluohq
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build all generators
        run: nix build .#all

      - name: Create release archives
        run: |
          mkdir -p release

          # Java
          tar -czf release/java-compliance-${{ github.ref_name }}.tar.gz -C result/java .

          # TypeScript
          tar -czf release/typescript-compliance-${{ github.ref_name }}.tar.gz -C result/typescript .

          # Python
          tar -czf release/python-compliance-${{ github.ref_name }}.tar.gz -C result/python .

          # Go
          tar -czf release/go-compliance-${{ github.ref_name }}.tar.gz -C result/go .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          body: |
            # Compliance as Code ${{ github.ref_name }}

            Generated compliance code for Java, TypeScript, Python, and Go.

            ## What's Included

            - **Java**: Annotations for Spring Boot, Quarkus, and vanilla Java
            - **TypeScript**: Decorators for NestJS, Express, and plain TypeScript
            - **Python**: Decorators for FastAPI, Django, and plain Python
            - **Go**: Context-based evidence for net/http and any Go framework

            ## Frameworks

            - GDPR (22 controls)
            - SOC 2 (8 controls)
            - HIPAA (11 controls)
            - FedRAMP (16 controls)
            - ISO 27001 (14 controls)
            - PCI-DSS (24 controls)

            ## Quick Start

            ```bash
            # Download and extract
            curl -L https://github.com/fluohq/compliance-as-code/releases/download/${{ github.ref_name }}/java-compliance-${{ github.ref_name }}.tar.gz | tar xz

            # Or use Nix directly
            nix build github:fluohq/compliance-as-code#java-gdpr
            ```

            See [README.md](https://github.com/fluohq/compliance-as-code) for full documentation.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
